### ISSUE TITLE
Add max_retries options to configure Net::HTTP idempotent request retry

### ISSUE THREAD

**Issue by dwiyanr** [drbrain/net-http-persistent#112]
After the release of ruby 2.5.0, `Net::HTTP` by default retry idempotent request in case of failure [ref](https://ruby-doc.org/stdlib-2.5.0/libdoc/net/http/rdoc/Net/HTTP.html#method-i-max_retries-3D). I think this can lead to unexpected behavior which needs to be configurable.
As far as I see, we cannot configure this in the current version of `net-http-persistent`. My suggestion is to add options for max_retries to pass to `Net::HTTP`

**Comment by drbrain** [comment]
Net::HTTP::Persistent no longer automatically retries requests as all versions of ruby it supports retry the requests automatically.

The option to enable retries will be removed in a future release, #100 is a PR to do this that is not yet merged.
