### ISSUE TITLE
Question: is there a way to disconnect the keepalived connections?

### ISSUE THREAD

**Issue by miyazakt** [drbrain/net-http-persistent#117]
Is there a way to disconnect the keepalived connections?
If the CNAME of DNS is changed, the connection is always kept, so the old one will continue to be accessed.

**Comment by drbrain** [comment]
Use [Net::HTTP::Persistent#reconnect](http://docs.seattlerb.org/net-http-persistent/Net/HTTP/Persistent.html#method-i-reconnect).

I'll update the documentation to note that it resets TLS/SSL and non-TLS/SSL connections.
