### ISSUE TITLE
Ruby 3.0 compatibility?

### ISSUE THREAD

**Issue by rgaufman** [drbrain/net-http-persistent#127]
When I try to bundle, I am getting this error:

```
net-http-persistent-4.0.0 requires ruby version ~> 2.3, which is incompatible with the current version, ruby 3.0.0p0
```

**Comment by maxwell** [comment]
it looks like master supports Ruby 3, so until a new version is cut, you can include 

```ruby
gem 'net-http-persistent', github: 'drbrain/net-http-persistent'
```

to get you unblocked on upgrading your app.

**Comment by rgaufman** [comment]
Yes, doesn't seem to help unfortunately:

```
Could not find gem 'net-http-persistent' in https://github.com/drbrain/net-http-persistent.git (at master@2379e37) or in gems cached in vendor/cache.
The source does not contain any versions of 'net-http-persistent'
```

**Comment by stevehodgkiss** [comment]
A new gem release should fix this. The fix is already in master, but it hasn't been released yet https://github.com/drbrain/net-http-persistent/pull/122

**Comment by jasl** [comment]
@tenderlove friendly ping, could you or someone can release a new version?

many gems depends on this so can't be used in Ruby 3.0 for now

**Comment by tenderlove** [comment]
Should be pushed now, sorry about that!
