### ISSUE TITLE
support connection pooling

### ISSUE THREAD

**Issue by bhenderson** [drbrain/net-http-persistent#49]
I've talked to you about this in the past, I just wanted a place to keep track of the discussion.

One of the issues we've run into is our production apps run more threads then some of our backends can handle, so we need a way to limit the number of connections.

One question I have is can the connections be shared between threads safely? I'm assuming not because you made it thread safe to begin with.

So, if we have 6 theads, and want to limit to 5 connections, do we make the 6th thread wait until one of the others releases the connection?

thanks,

**Comment by drbrain** [comment]
Now supported.
