### ISSUE TITLE
support for basic auth in get request?

### ISSUE THREAD

**Issue by maxstudener** [drbrain/net-http-persistent#75]
Not sure why this isn't working or maybe I am holding something wrong. My server is not getting the http basic auth creds, any idea?

``` ruby
http = Net::HTTP::Persistent.new
uri = URI( URI.escape( SCHEMA + '://' + USERNAME + ':' + PASS + '@' + DOMAIN + URL_PATH + "?" + params.map { |k, v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&') ))
http.read_timeout = 30
http.request uri
```

**Comment by BoGs** [comment]
Just build the request and attach the `basic_auth` to it as in this example.

You could do `http.request <your built request>`

http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Basic+Authentication

**Comment by drbrain** [comment]
Yes, or use mechanize wraps net-http-persistent and supports specifying which passwords belong to which URLs and realms.
