### ISSUE TITLE
Process::RLIMIT_NOFILE is not defined in Windows version

### ISSUE THREAD

**Issue by tunepolo** [drbrain/net-http-persistent#79]
When using in Windows environment, net-http-persistent raise uninitialized constant error.
Maybe caused by 'Process::RLIMIT_NOFILE' in lib/net/http/persistent.rb .

``` ruby
# The default connection pool size is 1/4 the allowed open files.

DEFAULT_POOL_SIZE = Process.getrlimit(Process::RLIMIT_NOFILE).first / 4
```

```
% ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

% irb
irb(main):001:0> Process::RLIMIT_NOFILE
NameError: uninitialized constant Process::RLIMIT_NOFILE
        from (irb):1
        from C:/ruby/2.2/i386-mingw32/bin/irb:11:in `<main>'
```

**Comment by ryancastro** [comment]
net-http-persistent is used by the Ruby implementation of Selenium Webdriver, so you'll likely see this issue popping up for windows users quite often (That's why I'm here).

**Comment by DiazHub** [comment]
Experiencing the same issue!
![image](https://cloud.githubusercontent.com/assets/20601252/21663840/88faf37c-d297-11e6-8a4f-1bae1717937c.png)

**Comment by Reppinger** [comment]
Also experiencing this issue in Windows using Selenium Webdriver.

**Comment by dcjohnson1989** [comment]
I also met such issue in windows using watir, any idea on fixing this?

**Comment by titusfortner** [comment]
Not that it is necessarily likely to help, but the code works fine on Windows 10, and appears to be an issue in Windows 8.

**Comment by jakauppila** [comment]
I'm running into this problem.

```
require 'net/http/persistent'

puts 'hello world'
```

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:205:in `<class:Persistent>': uninitialized constant Process::RLIMIT_NOFILE (NameError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:190:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from test.rb:1:in `<main>'
```

**Comment by martindouglasj** [comment]
What's the ETA on getting @jakauppila's pull request merged in? Still experiencing issue on Windows 10.

**Comment by srg0** [comment]
just change the library as mentioned here
*\Ruby2.*\lib\ruby\gems\2.*\gems\net-http-persistent-3.0.0\lib\net\http\persistent.rb
 https://github.com/drbrain/net-http-persistent/pull/90/files

**Comment by MrDariusAD** [comment]
still having this issue on 3.0

**Comment by dsisnero** [comment]
Can we get this fixed and a new gem made?
