### ISSUE TITLE
Retry of idempotent requests not working?

### ISSUE THREAD

**Issue by timanovsky** [drbrain/net-http-persistent#89]
From reading the code it looks like you rely on default `Net::HTTP` behavior to retry idempotent requests. Can you confirm this?

If so, do not. Unfortunately a few libraries patch it to disable retries, e.g.: https://github.com/aws/aws-sdk-ruby/blob/082ea490f63225c159cce9639ccd293d2433044a/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L13

**Comment by grosser** [comment]
@tenderlove / @drbrain  can we remove the whole retry logic ?
... regular faraday fails with Faraday::ConnectionFailed on timeout and once I add persistent adapter it fails with Faraday::TimeoutError, would prefer it to behave exactly like regular net-http :(

**Comment by drbrain** [comment]
I think the retry code that started in net-http-persistent now exists in all versions of net-http in supported rubies so it can be removed from net-http-persistent

**Comment by drbrain** [comment]
This feature is now removed, but will be controllable through #max_retries= in the 4.x series (which maps to Net::HTTP#max_retries=)
